; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.4-LPC-4 on Sun Sep 13 2020 01:26:58 GMT-0400 (Eastern Daylight Time)
M280 P0 S90														; retract BLTouch

