; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4-LPC-3 on Thu Sep 10 2020 10:24:58 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

